
spring:
  application:
    name: account-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url-path: /swagger-ui.html
    hostname: localhost

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slowCallRateThreshold: 2
    instances:
      accounts:
        base-config: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
    instances:
      accounts:
        base-config: default

server:
  port: 20200

path:
  accounts: /api/accounts
