
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/account_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging:
#  config: K:/bootcamp/project1/account-service/src/main/resources/logback.xml

swagger:
  title: Account Service API - Dev
  version: 1.0.0
  description: Account Microservice API

config:
  endpoint:
    enterprise-customers: lb://customer-service/api/enterprise-customers