
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bootcoin_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging:
#  config: K:/bootcamp/project1/customer-service/src/main/resources/logback.xml

swagger:
  title: Bootcoin Service API - Dev
  version: 1.0.0
  description: Bootcoin Microservice API

config:
  endpoint:
    accounts: lb://account-service/api/accounts