

spring:
  application:
    name: bootcoin-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url-path: /swagger-ui.html

server:
  port: 20500
