
spring:
  data:
    mongodb:
      uri: mongodb://mongoc:27017/customer_service

eureka:
  client:
    service-url:
      defaultZone: http://banking-discovery-server:8761/eureka

#logging:
#  config: K:/bootcamp/project1/customer-service/src/main/resources/logback.xml

swagger:
  title: Customer Service API - Prod

config:
  endpoint:
    accounts: lb://account-service/api/accounts
