
spring:
  data:
    mongodb:
      uri: mongodb://mongoc:27017/movement_service

eureka:
  client:
    service-url:
      defaultZone: http://banking-discovery-server:8761/eureka

#logging:
#  config: K:/bootcamp/project1/movement-service/src/main/resources/logback.xml

swagger:
  title: Movement Service API - Prod
  version: 1.0.0
  description: Movement Microservice API

config:
  endpoint:
    accounts: lb://account-service/api/accounts