
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/movement_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging:
#  config: K:/bootcamp/project1/movement-service/src/main/resources/logback.xml

swagger:
  title: Movement Service API - Dev