
spring:
  application:
    name: report-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url-path: /swagger-ui.html
    hostname: localhost

server:
  port: 20400

path:
  reports: /api/reports